"""initial schema

Revision ID: 0bb7a7326a13
Revises: 
Create Date: 2026-10-08 14:28:57.446223
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bb7a7326a13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('wiki', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('river', sa.String(length=64), nullable=False),
    sa.Column('water_body_type', sa.String(length=16), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method_level', sa.Integer(), nullable=False),
    sa.Column('method_note', sa.String(length=128), nullable=False),
    sa.Column('overall_grade', sa.Integer(), nullable=True),
    sa.Column('deciding_factors', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_code', sa.String(length=16), nullable=False),
    sa.Column('standard_no', sa.String(length=32), nullable=False),
    sa.Column('water_body_type', sa.String(length=16), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('limit_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['indicator_code'], ['indicator.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_code', 'standard_no', 'water_body_type', 'grade', name='uq_standard_limit')
    )
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('indicator_code', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_code'], ['indicator.code'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'indicator_code', name='uq_measurement')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    op.drop_table('standard_limit')
    op.drop_table('sample')
    op.drop_table('site')
    op.drop_table('indicator')
    # ### end Alembic commands ###
